// ============================================================
// API Client — barrel export
// ============================================================

export { getToken, setToken, clearToken, isAuthenticated, req } from './core';
export type { AuthProfileData, ChatAttachmentPayload } from './methods';
export type {
  Payment,
  AgentFeature,
  Agent,
  AdminPayment,
  AgentMailboxInfo,
  AgentMailDirection,
  AgentMailMessage,
  AgentMailRuntime,
  AgentMailSettings,
  AgentPassport,
  AgentPassportChainType,
  AgentPassportNetwork,
  AgentPassportNetworkId,
  AgentPassportPaymentRail,
  AgentPassportStatus,
  AgentWalletNativeBalance,
  AgentWalletNetworkBalance,
  AgentWalletPrivateKeyResponse,
  AgentWalletsResponse,
  AgentWalletTokenBalance,
  ChatMessage,
  ChatSessionSummary,
  GetAgentMailboxResponse,
  GetAgentMailMessagesResponse,
  SendAgentMailBody,
  SendAgentMailResponse,
  SpawnAgent,
  SpawnAgentsResponse,
  SpawnCreateAgentBody,
  SpawnDepositBody,
  SpawnDepositResponse,
  SpawnDna,
  SpawnEvent,
  SpawnEventsResponse,
  SpawnPaymentInstructions,
  SpawnPositionsResponse,
  SpawnStatusResponse,
  SpawnTrade,
  SpawnTradesResponse,
  TicketStatus,
  TicketCategory,
  TicketPriority,
  TicketMessage,
  Ticket,
  UpdateAgentMailSettingsBody,
  UpdateAgentMailSettingsResponse,
  FunnelResponse,
  ChurnRadarResponse,
  ReferralLeaderboardResponse,
  SignupHeatmapResponse,
  ErrorRateResponse,
  WsCountResponse,
  LlmStatsResponse,
  AdminEgressEventsResponse,
  AgentEgressEventsResponse,
  AdminIdleOverviewResponse,
} from './types';
export { api } from './methods';
