// ============================================================
// API Client — barrel export
// ============================================================

export { getToken, setToken, clearToken, isAuthenticated, req } from "./core";
export type { AuthProfileData, ChatAttachmentPayload } from "./methods";
export type {
  Payment,
  AgentFeature,
  Agent,
  AgentCommCallBody,
  AgentCommCallResponse,
  AgentCommCandidate,
  AgentCommDiscoverResponse,
  AgentGithubConnectStartResponse,
  AgentGithubRepoListItem,
  AgentGithubReposResponse,
  AgentGithubTestResponse,
  AgentCommLog,
  AgentCommLogsResponse,
  AgentCommPermission,
  AgentCommPermissionsResponse,
  AdminPayment,
  AgentMailboxInfo,
  AgentMailDirection,
  AgentMailMessage,
  AgentMailRuntime,
  AgentMailSettings,
  AgentPassport,
  AgentPassportChainType,
  AgentPassportNetwork,
  AgentPassportNetworkId,
  AgentPassportPaymentRail,
  AgentPassportStatus,
  AgentWalletNativeBalance,
  AgentWalletNetworkBalance,
  AgentWalletPrivateKeyResponse,
  AgentWalletsResponse,
  AgentWalletTokenBalance,
  AdminConduitExemptionWallet,
  AdminConduitOverviewResponse,
  AdminConduitProviderRow,
  AdminConduitSettlementRow,
  ChatMessage,
  ChatSessionSummary,
  GetAgentMailboxResponse,
  GetAgentMailMessagesResponse,
  SendAgentMailBody,
  SendAgentMailResponse,
  KausalayerCallBody,
  KausalayerCallResponse,
  KausalayerConfigBody,
  KausalayerConfigStatus,
  KausalayerHealthResponse,
  KausalayerResourceResult,
  KausalayerResourcesResponse,
  KausalayerTool,
  KausalayerToolsResponse,
  XonaCallBody,
  XonaCallResponse,
  XonaConfigStatus,
  XonaDiscoverBody,
  XonaDiscoverResponse,
  XonaToolId,
  XonaToolSummary,
  ConduitConfigBody,
  ConduitConfigStatus,
  ConduitManifestResponse,
  ConduitPayoutMode,
  ConduitProviderActionResponse,
  ConduitProviderPatchBody,
  ConduitProviderRegistration,
  ConduitProvidersResponse,
  ConduitProtocolInfoResponse,
  ConduitRegisterProviderBody,
  ConduitRegisterProviderResponse,
  TicketStatus,
  TicketCategory,
  TicketPriority,
  TicketMessage,
  Ticket,
  UpdateAgentMailSettingsBody,
  UpdateAgentMailSettingsResponse,
  FunnelResponse,
  ChurnRadarResponse,
  ReferralLeaderboardResponse,
  SignupHeatmapResponse,
  ErrorRateResponse,
  WsCountResponse,
  LlmStatsResponse,
  AdminEgressEventsResponse,
  AgentEgressEventsResponse,
  AdminIdleOverviewResponse,
} from "./types";
export { api } from "./methods";
