import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | Hatcher',
  description: 'Terms of Service for the Hatcher AI agent hosting platform.',
};

export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-[var(--bg-base)]">
      <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
        {/* Header */}
        <div className="mb-12">
          <h1 className="text-3xl sm:text-4xl font-bold text-[var(--text-primary)] mb-3" style={{ fontFamily: 'var(--font-display), system-ui, sans-serif' }}>
            Terms of Service
          </h1>
          <p className="text-sm text-[var(--text-muted)]">Last updated: March 30, 2026</p>
        </div>

        <div className="prose-custom space-y-10 text-[var(--text-secondary)] text-[15px] leading-relaxed">
          {/* 1 */}
          <section>
            <h2 className="text-xl font-semibold text-[var(--text-primary)] mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using the Hatcher platform at{' '}
              <a href="https://hatcher.host" className="text-cyan-400 hover:underline">hatcher.host</a>{' '}
              (the &ldquo;Service&rdquo;), you agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree to these Terms, do not use the Service.
            </p>
            <p className="mt-3">
              These Terms constitute a legally binding agreement between you and HatcherLabs (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;). We may update these Terms from time to time, and your continued use of the Service constitutes acceptance of any changes.
            </p>
          </section>

          {/* 2 */}
          <section>
            <h2 className="text-xl font-semibold text-[var(--text-primary)] mb-3">2. Description of Service</h2>
            <p>
              Hatcher is a managed AI agent hosting platform. The Service allows you to deploy, configure, and run AI agents across multiple frameworks (including OpenClaw, Hermes, ElizaOS, and Milady) and connect them to various platforms such as Telegram, Discord, Twitter, WhatsApp, and Slack.
            </p>
            <p className="mt-3">
              We provide the infrastructure, container orchestration, and optional LLM access to power your agents. You are responsible for configuring your agents and providing any third-party API keys or platform tokens required for integrations.
            </p>
          </section>

          {/* 3 */}
          <section>
            <h2 className="text-xl font-semibold text-[var(--text-primary)] mb-3">3. Account Registration</h2>
            <p>
              To use the Service, you must create an account by providing a valid email address and password. You must be at least 18 years of age to create an account and use the Service.
            </p>
            <p className="mt-3">
              You are responsible for maintaining the confidentiality of your account credentials, including any API keys generated through the platform. You agree to notify us immediately of any unauthorized use of your account.
            </p>
            <p className="mt-3">
              You may optionally link a Solana wallet address to your account for payment purposes. We do not store private keys or seed phrases.
            </p>
          </section>

          {/* 4 */}
          <section>
            <h2 className="text-xl font-semibold text-[var(--text-primary)] mb-3">4. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1.5">
              <li>Engage in any illegal activity or facilitate illegal actions through your agents</li>
              <li>Distribute malware, spam, or harmful content</li>
              <li>Abuse platform resources, including attempting to bypass usage limits or resource quotas</li>
              <li>Scrape, crawl, or harvest data from the Service or other users</li>
              <li>Impersonate other individuals or entities</li>
              <li>Interfere with or disrupt the Service or its infrastructure</li>
              <li>Attempt to gain unauthorized access to other users&apos; accounts, agents, or data</li>
              <li>Use the Service to generate content that violates applicable laws or third-party rights</li>
            </ul>
            <p className="mt-3">
              We reserve the right to suspend or terminate accounts that violate these terms without prior notice.
            </p>
          </section>

          {/* 5 */}
          <section>
            <h2 className="text-xl font-semibold text-[var(--text-primary)] mb-3">5. Agent Content &amp; Responsibility</h2>
            <p>
              You are solely responsible for the behavior, output, and content generated by any AI agents you deploy on the platform. This includes messages sent through connected platforms (Telegram, Discord, Twitter, etc.), files created within agent workspaces, and any actions performed by your agents.
            </p>
            <p className="mt-3">
              HatcherLabs does not monitor or control the output of your agents in real time and is not liable for any harm, damages, or violations caused by your agents&apos; behavior.
            </p>
            <p className="mt-3">
              You agree to promptly address any issues arising from your agents&apos; behavior and to comply with the terms of service of any third-party platforms your agents interact with.
            </p>
          </section>

          {/* 6 */}
          <section>
            <h2 className="text-xl font-semibold text-[var(--text-primary)] mb-3">6. Intellectual Property</h2>
            <p>
              You retain ownership of all content, configurations, and data you create on the platform. HatcherLabs does not claim ownership of your agent configurations, custom prompts, or generated content.
            </p>
            <p className="mt-3">
              The Hatcher platform, including its design, code, logos, and documentation, is the intellectual property of HatcherLabs and is protected by applicable copyright and trademark laws. You may not copy, modify, or distribute any part of the platform without our written permission.
            </p>
          </section>

          {/* 7 */}
          <section>
            <h2 className="text-xl font-semibold text-[var(--text-primary)] mb-3">7. Payment Terms</h2>
            <p>
              Certain features of the Service require payment. Prices are listed in USD and may be paid using SOL (Solana), platform tokens, or USD via Stripe. Cryptocurrency prices are converted at the current market rate via Jupiter at the time of transaction.
            </p>
            <p className="mt-3">
              Subscriptions are billed monthly. Add-on purchases may be one-time or recurring depending on the product. All sales are final unless otherwise required by applicable law.
            </p>
            <p className="mt-3">
              We reserve the right to change pricing at any time. Existing subscribers will be notified of price changes at least 30 days in advance.
            </p>
          </section>

          {/* 8 */}
          <section>
            <h2 className="text-xl font-semibold text-[var(--text-primary)] mb-3">8. Free Tier &amp; Paid Plans</h2>
            <p>
              Hatcher offers a free tier that includes one agent with limited daily messages using our hosted LLM. Free tier agents run on shared resources and are subject to auto-sleep after periods of inactivity.
            </p>
            <p className="mt-3">
              Paid plans (Basic, Pro) unlock additional agents, higher message limits, dedicated resources, and premium features. Full plan details are available on our{' '}
              <Link href="/pricing" className="text-cyan-400 hover:underline">Pricing page</Link>.
            </p>
            <p className="mt-3">
              Bringing your own API key (BYOK) for LLM providers bypasses our daily message limits on all tiers, giving you unlimited messages at no additional cost from Hatcher.
            </p>
          </section>

          {/* 9 */}
          <section>
            <h2 className="text-xl font-semibold text-[var(--text-primary)] mb-3">9. Service Availability</h2>
            <p>
              We strive to maintain high availability of the Service but do not guarantee uninterrupted access. The Service is provided on a &ldquo;best effort&rdquo; basis, and we may perform maintenance, updates, or experience outages from time to time.
            </p>
            <p className="mt-3">
              No Service Level Agreement (SLA) is provided for the free tier. Paid plans receive priority support but are not covered by a formal SLA at this time. We will communicate scheduled maintenance through our status page and Discord community when possible.
            </p>
          </section>

          {/* 10 */}
          <section>
            <h2 className="text-xl font-semibold text-[var(--text-primary)] mb-3">10. Data &amp; Privacy</h2>
            <p>
              Your use of the Service is also governed by our{' '}
              <Link href="/privacy" className="text-cyan-400 hover:underline">Privacy Policy</Link>,
              which describes how we collect, use, and protect your personal information. By using the Service, you consent to the practices described in the Privacy Policy.
            </p>
          </section>

          {/* 11 */}
          <section>
            <h2 className="text-xl font-semibold text-[var(--text-primary)] mb-3">11. Termination</h2>
            <p>
              You may delete your account at any time by contacting support. Upon deletion, your agents will be stopped and your data will be removed within 30 days.
            </p>
            <p className="mt-3">
              We reserve the right to suspend or terminate your account at any time if you violate these Terms, engage in abusive behavior, or if we determine that your use of the Service poses a risk to other users or our infrastructure. In cases of severe violations, termination may occur without prior notice.
            </p>
            <p className="mt-3">
              Upon termination, your right to use the Service ceases immediately. We are not obligated to provide refunds for any pre-paid subscription periods.
            </p>
          </section>

          {/* 12 */}
          <section>
            <h2 className="text-xl font-semibold text-[var(--text-primary)] mb-3">12. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by applicable law, HatcherLabs and its officers, employees, and affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or relating to your use of the Service.
            </p>
            <p className="mt-3">
              This includes, but is not limited to, damages for loss of profits, data, goodwill, or other intangible losses, even if we have been advised of the possibility of such damages.
            </p>
            <p className="mt-3">
              Our total aggregate liability for all claims arising out of or relating to these Terms or the Service shall not exceed the amount you paid us in the 12 months preceding the claim.
            </p>
          </section>

          {/* 13 */}
          <section>
            <h2 className="text-xl font-semibold text-[var(--text-primary)] mb-3">13. Changes to Terms</h2>
            <p>
              We may revise these Terms at any time by posting an updated version on this page. The &ldquo;Last updated&rdquo; date at the top of this page indicates when the Terms were last modified.
            </p>
            <p className="mt-3">
              Material changes will be communicated via email or a prominent notice on the platform. Your continued use of the Service after changes are posted constitutes acceptance of the revised Terms.
            </p>
          </section>

          {/* 14 */}
          <section>
            <h2 className="text-xl font-semibold text-[var(--text-primary)] mb-3">14. Contact Information</h2>
            <p>
              If you have any questions about these Terms, please contact us at:
            </p>
            <ul className="mt-3 space-y-1.5">
              <li>Email: <a href="mailto:support@hatcher.host" className="text-cyan-400 hover:underline">support@hatcher.host</a></li>
              <li>Discord: <a href="https://discord.gg/7tY3HjKjMc" target="_blank" rel="noopener noreferrer" className="text-cyan-400 hover:underline">discord.gg/7tY3HjKjMc</a></li>
              <li>Support page: <Link href="/support" className="text-cyan-400 hover:underline">hatcher.host/support</Link></li>
            </ul>
          </section>
        </div>
      </div>
    </main>
  );
}
